### ISSUE TITLE
how to add tags for articles?

### ISSUE THREAD

**Issue by Tricrepe** [gothinkster/react-redux-realworld-example-app#151]
I tried many times to enter tags for new post. But it doesn't work. Does the tag need a format?

**Comment by jefflafay** [comment]
@Tricrepe did you figure it out? I was looking for the same information

**Comment by cirosantilli** [comment]
I reproduce with node express as described at: https://github.com/gothinkster/node-express-realworld-example-app/pull/116 

I then put a print on the server:

```
diff --git a/routes/api/articles.js b/routes/api/articles.js
index c17ca61..401448f 100644
--- a/routes/api/articles.js
+++ b/routes/api/articles.js
@@ -126,6 +126,8 @@ router.post('/', auth.required, function(req, res, next) {
   User.findById(req.payload.id).then(function(user){
     if (!user) { return res.sendStatus(401); }
 
+    console.error('asdf');
+    console.error(req.body.article);
     var article = new Article(req.body.article);
 
     article.author = user;
```

and when I create a new article it gives:

```
{ title: 'ti3', description: 'ab3', body: 'bo3', tagList: [] }
```

which suggests that it is a bug in React not sending the tags.

Ermm, actually the reference instance also has broken tags: https://demo.realworld.io/#/ ... but it is based on Angular instead of React...

**Comment by cirosantilli** [comment]
Found it out: you have to hit the Enter key, updated that info in my above comment.
